### ISSUE TITLE
Base Networking Layer

### ISSUE THREAD

**Issue by ryansheh** [LibertyDSNP/dsnp-wallet-swift#30]
TBD

**Comment by rig-0** [comment]
The goal of this issue is to set ourselves up with some scaffolding of a base networking layer.

Requirements:
* Convenient methods for writing simple REST API requests
* The ability to parse responses in JSON, String, or provided format
* Simple caching layer
* Mechanism for supporting mocked responses against targeted requests
* Unit tests that verify our core logic, where any outgoing requests are mocked
